---
- name: Include woodpecker vars
  ansible.builtin.include_vars:
    file: "{{ woodpecker_mode }}"
    name: woodpecker_config

- name: Create project directory
  ansible.builtin.file:
    path: /srv/docker-compose/woodpecker
    state: directory
    mode: '0755'

- name: Copy docker compose file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /srv/docker-compose/woodpecker/{{ item }}
    mode: 0644
  with_items:
    - docker-compose.yml

- name: Copy ENV file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /srv/docker-compose/woodpecker/{{ item }}
    mode: 0644
  with_items:
    - .env

- name: Deploy docker compose stack
  community.docker.docker_compose:
    project_src: /srv/docker-compose/woodpecker/
    files:
      - docker-compose.yml
