---
- name: Include backup vars
  ansible.builtin.include_vars:
    file: backup.yml
    name: backup_config

- name: Install restic
  ansible.builtin.dnf:
    name:
      - restic
    state: present

- name: Create restic directory
  ansible.builtin.file:
    path: /opt/restic
    state: directory
    mode: '0755'

- name: Copy scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /opt/restic/{{ item }}
    mode: 0755
  loop:
    - backup.sh
    - restore.sh
    - check.sh

- name: Create log folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  loop:
    - /var/log/restic

- name: Create empty log file
  ansible.builtin.copy:
    content: ""
    dest: /var/log/restic/backup.log
    force: false
    group: sys
    owner: root
    mode: 0644

- name: Add daily cronjob for backups
  ansible.builtin.cron:
    name: "restic backup"
    user: root
    minute: "0"
    hour: "4"
    job: "/opt/restic/backup.sh >> /var/log/restic/backup.log"
