---
- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: yes

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Enable ssh
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled

- name: Allow custom SSH port
  ansible.posix.firewalld:
    zone: public
    port: '{{ sshd_port }}/tcp'
    state: enabled

- name: Allow all access to web (80)
  ansible.posix.firewalld:
    port: '80/tcp'
    state: enabled
    zone: public

- name: Allow all access to web (443)
  ansible.posix.firewalld:
    port: '443/tcp'
    state: enabled
    zone: public

- name: Allow all access to node_exporter
  ansible.posix.firewalld:
    port: '9100/tcp'
    state: enabled
    zone: public

- name: Allow SSH access to Forgejo
  ansible.posix.firewalld:
    port: '{{ forgejo_ssh_port }}/tcp'
    state: enabled
    zone: public

- name: Allow masquerade to allow container to container communication
  ansible.posix.firewalld:
    masquerade: true
    state: enabled
    permanent: true
    zone: public

- name: reload firewalld
  ansible.builtin.command: firewall-cmd --reload