---
- name: Install ansible via dnf
  ansible.builtin.dnf:
    pkg:
      - ansible
- name: Install dnf dependencies
  ansible.builtin.dnf:
    pkg:
      - python3-docker
      - python3-pip
- name: Install docker dependencies via pip
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
