---
# https://docs.docker.com/engine/install/debian/
- name: Install Docker dependencies
  ansible.builtin.dnf:
    name:
      - ca-certificates
      - curl
      - gnupg2
      - lsb_release
      - yum-utils
    state: present

- name: Remove Conflicting packages
  ansible.builtin.dnf:
    name:
      - podman
      - buildah
    state: absent

- name: Add rpm signing key
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add docker repo repository
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Add user {{ user_name }} to docker group
  ansible.builtin.user:
    name: '{{ user_name }}'
    groups: docker
    append: true

- name: enable docker
  ansible.builtin.service:
    name: docker
    enabled: yes

- name: start docker
  ansible.builtin.service:
    name: docker
    state: started


- name: Remove unused Docker resources from the system
  command: docker image prune -a -f
